services:

  postgres:
    image: postgres:16
    container_name: mdp_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5433:5432"

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mdp_pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres


  airflow:
    image: apache/airflow:3.3.0
    container_name: mdp_airflow

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

    ports:
      - "8080:8080"

    command: standalone


volumes:
  postgres-db-volume: